#!/usr/bin/python
# -*- coding: utf-8 -*-

custom_tags = [
(u'公屋',u'公屋',u'Public housing',),
(u'住戶數目',u'住户数目',u'Number of households',),
(u'賣地',u'卖地',u'Land Sale',),
(u'單位數目',u'单位数目',u'Flat count',),
(u'按揭',u'按揭',u'Mortgage',),
(u'面積',u'面积',u'Area',),
(u'公營房屋',u'公营房屋',u'Public housing',),
(u'落成數量',u'落成数量',u'Completion count',),
(u'居屋',u'居屋',u'Home ownership scheme',),
(u'房委會',u'房委会',u'Housing Authority',),
(u'房屋類型',u'房屋类型',u'Property Type',),
(u'私樓',u'私楼',u'Private housing',),
(u'租金',u'租金',u'Rent',),
(u'一手私人住宅',u'一手私人住宅',u'First-hand private housing',),
(u'人口',u'人口',u'Population',),
(u'預測',u'预测',u'Prediction',),
(u'入息',u'入息',u'Income',),
(u'分區',u'分区',u'Region',),
(u'土地',u'土地',u'Land Sale',),
(u'數目',u'数目',u'Count',),
(u'用途',u'用途',u'Land use',),
(u'私營房屋',u'私营房屋',u'Private housing',),
(u'人數',u'人数',u'People count',),
(u'住戶人數',u'住户人数',u'Number of households',),
(u'劏房',u'劏房',u'Boudoir',),
(u'售價',u'售价',u'Price',),
(u'土地供應',u'土地供应',u'Land supply',),
(u'帳目',u'帐目',u'Account',),
(u'建屋量',u'建屋量',u'House building count',),
(u'建築成本',u'建筑成本',u'Building cost',),
(u'房協',u'房协',u'HK Housing society',),
(u'房屋需求',u'房屋需求',u'Housing demand',),
(u'換樓',u'换楼',u'Changing home',),
(u'申請數目',u'申请数目',u'Number of applications',),
(u'研究報告',u'研究报告',u'Research report',),
(u'編配',u'编配',u'Arrangement',),
(u'落成量',u'落成量',u'Completion count',),
(u'財政',u'财政',u'Finance',),
(u'一手買賣',u'一手买卖',u'First hand trade',),
(u'中位數',u'中位数',u'Median',),
(u'中轉屋',u'中转屋',u'Transit house',),
(u'二手私人住宅',u'二手私人住宅',u'Second-hand private residence',),
(u'交易',u'交易',u'Transaction',),
(u'人均收入',u'人均收入',u'Per capita income',),
(u'人均開支',u'人均开支',u'Per capita expenditure',),
(u'住宅數目',u'住宅数目',u'Number of housing',),
(u'住戶',u'住户',u'Household',),
(u'供款',u'供款',u'Loan pay',),
(u'利率',u'利率',u'interest rate',),
]

