#!/usr/bin/python
# -*- coding: utf-8 -*-

regions_tags = [
            (u'全港'    , u'全港'  , u'Whole HK'),
            (u'港島'    , u'港岛'  , u'HK Island'),
            (u'九龍'    , u'九龙'  , u'Kowloon'),
            (u'新界'    , u'新界'  , u'NT'),
            (u'地點'    , u'地点'  , u'Point'),
            (u'中西區'  , u'中西区' , u'Central and Western District'),
            (u'東區'    , u'东区'  ,u'Eastern District'),
            (u'南區'    , u'南区'  ,u'Southern District'),
            (u'灣仔區'  , u'湾仔区' ,u'Wan Chai District'),
            (u'深水埗區', u'深水埗区'  ,u'Sham Shui Po District'),
            (u'九龍城區', u'九龙城区'  ,u'Kowloon City District'),
            (u'觀塘區'  , u'观塘区'  ,u'Kwun Tong District'),
            (u'黃大仙區', u'黄大仙区'  ,u'Wong Tai Sin District'),
            (u'油尖旺區', u'油尖旺区'  ,u'Yau Tsim Mong District'),
            (u'離島區'  , u'离岛区'  ,u'Islands District'),
            (u'葵青區'  , u'葵青区'  ,u'Kwai Tsing District'),
            (u'北區'    , u'北区'   ,u'North District'),
            (u'西貢區'  , u'西贡区'  ,u'Sai Kung District'),
            (u'沙田區'  , u'沙田区'  ,u'Sha Tin District'),
            (u'大埔區'  , u'大埔区'  ,u'Tai Po District'),
            (u'荃灣區'  , u'荃湾区'  ,u'Tsuen Wan District'),
            (u'屯門區'  , u'屯门区'  ,u'Tuen Mun District'),
            (u'元朗區'  , u'元朗区'  ,u'Yuen Long District'),
            (u'非本地'  , u'非本地'  ,u'Non local'),
        ]

datasources_tags = [
        (u'運輸及房屋局'       , u'运输及房屋局'           , u'Transport and Housing Bureau'),
        (u'房屋委員會'         , u'房屋委员会'            , u'Hong Kong Housing Authority'), 
        (u'立法會'              , u'立法会'                , u'LegCo'), 
        (u'金融管理局'           , u'金融管理局'            , u'Hong Kong Monetary Authority'), 
        (u'一手住宅物業銷售監管局' , u'一手住宅物业销售监管局'  , u'Sales of First-hand Residential Properties Authority'), 
        (u'人口普查'            , u'人口普查'              , u'Population census'), 
        (u'香港政府一站通'       , u'香港政府一站通'         , u'GovHK'),  
        (u'私人機構'            , u'私人机构'              , u'Private Agency'), 
        (u'香港按揭證券有限公司'  , u'香港按揭证券有限公司'    , u'The Hong Kong Mortgage Corporation Limited'),
        (u'中原地產'  , u'中原地产'    , u'Centraline Property'),
        (u'香港房屋協會'  , u'香港房屋协会'    , u'Hong Kong Housing Society'),
        (u'統計處'  , u'统计处'    , u'Census and Statistics Department'),
        (u'香港中文大學'  , u'香港中文大学'    , u'The Chinese University of Hong Kong'),
        (u'發展局', u'发展局', u'Development Bureau'), 
        (u'環境局', u'环境局', u'Environment Bureau'), 
        (u'財經事務及庫務局', u'财经事务及库务局', u'Financial Services and the Treasury Bureau'), 
        (u'創新及科技局', u'创新及科技局', u'Innovation and Technology Bureau'), 
        (u'勞工及福利局', u'劳工及福利局', u'Labour and Welfare Bureau'), 
        (u'運輸及房屋局', u'运输及房屋局', u'Transport and Housing Bureau'), 
        (u'建築署', u'建筑署', u'Architectural Services Department'), 
        (u'屋宇署', u'屋宇署', u'Buildings Department'), 
        (u'政府統計處', u'政府统计处', u'Census and Statistics Department'), 
        (u'土木工程拓展署', u'土木工程拓展署', u'Civil Engineering and Development Department'), 
        (u'公司註冊處', u'公司注册处', u'Companies Registry'), 
        (u'機電工程署', u'机电工程署', u'Electrical and Mechanical Services Department'), 
        (u'環境保護署', u'环境保护署', u'Environmental Protection Department'), 
        (u'食物環境衞生署', u'食物环境衞生署', u'Food and Environmental Hygiene Department'), 
        (u'政府產業署', u'政府产业署', u'Government Property Agency'), 
        (u'衞生署', u'衞生署', u'"Health'), 
        (u'房屋署', u'房屋署', u'Housing Department'), 
        (u'政府新聞處', u'政府新闻处', u'Information Services Department'), 
        (u'稅務局', u'税务局', u'Inland Revenue Department'), 
        (u'勞工處', u'劳工处', u'Labour Department'), 
        (u'土地註冊處', u'土地注册处', u'Land Registry'), 
        (u'地政總署', u'地政总署', u'Lands Department'), 
        (u'康樂及文化事務署', u'康乐及文化事务署', u'Leisure and Cultural Services Department'), 
        (u'規劃署', u'规划署', u'Planning Department'), 
        (u'香港電台', u'香港电台', u'Radio Television Hong Kong'), 
        (u'差餉物業估價署', u'差饷物业估价署', u'Rating and Valuation Department'), 
        (u'社會福利署', u'社会福利署', u'Social Welfare Department'), 
        (u'運輸署', u'运输署', u'Transport Department'), 
        (u'庫務署', u'库务署', u'Treasury'), 
        (u'競爭事務委員會', u'竞争事务委员会', u'Competition Commission'), 
        (u'消費者委員會', u'消费者委员会', u'Consumer Council'), 
        (u'地產代理監管局', u'地产代理监管局', u'Estate Agents Authority'), 
        (u'醫院管理局', u'医院管理局', u'Hospital Authority'), 
        (u'強制性公積金計劃管理局', u'强制性公积金计划管理局', u'Mandatory Provident Fund Schemes Authority'),
        (u'領匯.領展', u'领汇.领展', u'Link REIT'), 
        (u'領匯監察', u'领汇监察', u'Link Watch'), 
        (u'區域法院', u'区域法院', u'District Court'), 
        (u'城市規劃委員會', u'城市规划委员会', u'Town Planing Board'), 
        (u'審計署', u'审计署', u'Audit Commission'), 
        (u'市區更新地區諮詢平台', u'市区更新地区咨询平台', u'District Urban Renewal Forum'), 
        (u'市區更新基金', u'市区更新基金', u'Urban Renewal Fund'), 
        (u'市區重建局', u'市区重建局', u'Urban Renewal Authority'), 
        (u'規劃環境地政科', u'规划环境地政科', u'Planning, Environment and Lands Bureau'), 
        (u'香港大學', u'香港大学', u'The University of Hong Kong'), 
	(u'食物及衛生局',u'食物及卫生局',u'Food and Health Bureau',),
	(u'衛生署',u'卫生署',u'Department of Health',),
	(u'扶貧委員會',u'扶贫委员会',u'Commission on Poverty',),
	(u'香港理工大學應用社會科學系社會政策研究中心',u'香港理工大学应用社会科学系社会政策研究中心',u'Centre for Social Policy Studies, The Hong Kong Polytechnic University',),
	(u'香港大學民意研究計劃',u'香港大学民意研究计划',u'Public Opinion Program, The University of Hong Kong',),
	(u'強積性公積金計劃管理局',u'强积性公积金计划管理局',u'Mandatory Provident Fund Schemes Authority',),
	(u'香港社會服務聯會',u'香港社会服务联会',u'The Hong Kong Council of Social Service',),
	(u'香港公開大學',u'香港公开大学',u'The Open University of Hong Kong',),
	(u'公共專業聯盟',u'公共专业联盟',u'The Professional Commons',),
	(u'明愛荃灣社區中心',u'明爱荃湾社区中心',u'Caritas Community Cneter - Tuen Wan',),
	(u'香港浸會大學青年研究實踐中心',u'香港浸会大学青年研究实践中心',u'The Centre for Youth Research and Practice of Hong Kong Baptist University',),
	(u'公務員事務局',u'公务员事务局',u'Civil Service Bureau',),
	(u'樂施會',u'乐施会',u'Oxfam Hong Kong',),
	(u'香港年金有限公司',u'香港年金有限公司',u'HKMC Annuity Limited',),
	(u'香港特別行政區政府新聞公報',u'香港特别行政区政府新闻公报',u'HKSAR Government Press Release',),
        (u'其他', u'其他', u'Others'), 
        ]

updatefreqs_tags = [
        (u'5年'    , u'5年'      ,u'5-Yearly'),
        (u'每年'    , u'每年'     ,u'Yearly'), 
        (u'每半年'  , u'每半年'    ,u'Half-Yearly'),  
        (u'每月'    , u'每月'     ,u'Monthly'),
        (u'每季'    , u'每季'     ,u'Quarterly'),
        (u'每週'    , u'每週'     ,u'Weekly'),
        (u'不定期'  , u'不定期'    ,u'Irregular'),
        (u'一次性'   , u'一次性'   ,u'One-shot'), 
        (u'不再更新' , u'不再更新'  ,u'No longer updated'), 
        ]

custom_tags = [
(u'公屋',u'公屋',u'Public housing',),
(u'住戶數目',u'住户数目',u'Number of households',),
(u'賣地',u'卖地',u'Land Sale',),
(u'單位數目',u'单位数目',u'Flat count',),
(u'按揭',u'按揭',u'Mortgage',),
(u'面積',u'面积',u'Area',),
(u'公營房屋',u'公营房屋',u'Public housing',),
(u'落成數量',u'落成数量',u'Completion count',),
(u'居屋',u'居屋',u'Home ownership scheme',),
(u'房委會',u'房委会',u'Housing Authority',),
(u'房屋類型',u'房屋类型',u'Property Type',),
(u'私樓',u'私楼',u'Private housing',),
(u'租金',u'租金',u'Rent',),
(u'一手私人住宅',u'一手私人住宅',u'First-hand private housing',),
(u'人口',u'人口',u'Population',),
(u'預測',u'预测',u'Prediction',),
(u'入息',u'入息',u'Income',),
(u'分區',u'分区',u'Region',),
(u'土地',u'土地',u'Land Sale',),
(u'數目',u'数目',u'Count',),
(u'用途',u'用途',u'Land use',),
(u'私營房屋',u'私营房屋',u'Private housing',),
(u'人數',u'人数',u'People count',),
(u'住戶人數',u'住户人数',u'Number of households',),
(u'劏房',u'劏房',u'Boudoir',),
(u'售價',u'售价',u'Price',),
(u'土地供應',u'土地供应',u'Land supply',),
(u'帳目',u'帐目',u'Account',),
(u'建屋量',u'建屋量',u'House building count',),
(u'建築成本',u'建筑成本',u'Building cost',),
(u'房協',u'房协',u'HK Housing society',),
(u'房屋需求',u'房屋需求',u'Housing demand',),
(u'換樓',u'换楼',u'Changing home',),
(u'申請數目',u'申请数目',u'Number of applications',),
(u'研究報告',u'研究报告',u'Research report',),
(u'編配',u'编配',u'Arrangement',),
(u'落成量',u'落成量',u'Completion count',),
(u'財政',u'财政',u'Finance',),
(u'一手買賣',u'一手买卖',u'First hand trade',),
(u'中位數',u'中位数',u'Median',),
(u'中轉屋',u'中转屋',u'Transit house',),
(u'二手私人住宅',u'二手私人住宅',u'Second-hand private residence',),
(u'交易',u'交易',u'Transaction',),
(u'人均收入',u'人均收入',u'Per capita income',),
(u'人均開支',u'人均开支',u'Per capita expenditure',),
(u'住宅數目',u'住宅数目',u'Number of housing',),
(u'住戶',u'住户',u'Household',),
(u'供款',u'供款',u'Loan pay',),
(u'利率',u'利率',u'interest rate',),
]

